### ISSUE TITLE
segmentation fault  complexity

### ISSUE THREAD

**Issue by albertoferro** [thoughtbot/complexity#17]
Mac Monterrye with M1 proc

!!  segmentation fault  complexity

```
➜  ~ complexity install-configuration
[1]    43098 segmentation fault  complexity install-configuration
➜  ~ sudo complexity install-configuration
Password:
[1]    43120 segmentation fault  sudo complexity install-configuration
```

**Comment by joshuaclayton** [comment]
@albertoferro hello!

Could you give this a try while we update installation instructions?

```
brew uninstall complexity
brew install complexity --without-mimalloc
```

**Comment by joshuaclayton** [comment]
@albertoferro given the current M1 usage which I anticipate will increase over time, I've [updated our Homebrew formulae](https://github.com/thoughtbot/homebrew-formulae/pull/73) so that this should work out of the box for both Intel and Apple silicon.

Want to give this another go and let me know what happens?

**Comment by albertoferro** [comment]
@joshuaclayton works perfect thanks
